apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{name}"
  annotations:
    volume.beta.kubernetes.io/storage-class: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{size}"
