apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: podsecuritypolicy-for-{{ .Release.Name}}-{{ .Chart.Name }}
  namespace: demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: podsecuritypolicy
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name}}-{{ .Chart.Name }}
  namespace: demo
